# Generated by Django 2.0.7 on 2018-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20180806_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
