# Generated by Django 2.0.7 on 2018-08-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180809_2012'),
        ('diary', '0003_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_posts', models.ManyToManyField(blank=True, to='diary.Post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
