# Generated by Django 2.0.7 on 2018-08-06 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None),
        ),
    ]
